studySpec:
  metrics:
  - metricId: accuracy
    goal: MAXIMIZE
  parameters:
  - parameterId: max_iter
    discreteValueSpec:
      values:
      - 10
      - 20
  - parameterId: alpha
    doubleValueSpec:
      minValue: 1.0e-4
      maxValue: 1.0e-1
    scaleType: UNIT_LINEAR_SCALE
  # TODO

  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/qwiklabs-asl-03-2de90311f4ec/trainer_image:latest
      args:
      - --job_dir=gs://qwiklabs-asl-03-2de90311f4ec-kfp-artifact-store/jobs/forestcover_tuning_20230725_062241
      - --training_dataset_path=gs://qwiklabs-asl-03-2de90311f4ec-kfp-artifact-store/data/training/dataset.csv
      - --validation_dataset_path=gs://qwiklabs-asl-03-2de90311f4ec-kfp-artifact-store/data/validation/dataset.csv
      - --hptune
